# Generated by Django 4.0.4 on 2022-11-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppName', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
